- hosts: webserver
  tasks:
   - name: "Installing HTTPD WEBSERVER Software"
     package: 
      name: "httpd"
      state: present
   - name: "Install PHP Software"
     package:
      name: "php"
      state: present
   - name: "Deploying one Website"
     copy:
      src: /newWork/task3/index.php
      dest: /var/www/html/index.php 
   - name: "Exposing at port 80"
     firewalld:
      port: 80/tcp
      permanent: yes
      immediate: yes
      state: enabled
   - name:
     service:
      name: "httpd"
      state: restarted

